const now = Date.now();

export const mockSnapshot = {
  schemaVersion: 1,
  platform: "darwin",
  arch: "arm64",
  hostname: "workstation.local",
  refreshedAt: new Date(now).toISOString(),
  codex: {
    id: "codex",
    label: "Codex Desktop",
    installed: true,
    running: true,
    desktopPath: "/Applications/ChatGPT.app",
    cliPath: "/opt/homebrew/bin/codex",
    dataHome: "/Users/local/.codex",
    processes: [{ pid: 963, name: "codex", command: "codex app-server", elapsed: "01:44:57" }],
    totals: { inputTokens: 512880, outputTokens: 8624, cachedInputTokens: 336640, totalTokens: 521504 },
    stats: null,
    errors: [],
    sessions: [
      {
        id: "codex-1",
        title: "实现本地 AI 运行监控面板",
        latestContent: "正在接入会话状态变化，并检查浮窗提醒的触发时机。",
        cwd: "/Users/local/Projects/ai-monitor",
        model: "gpt-5.6-sol",
        effort: "high",
        status: "running",
        source: "Codex Desktop",
        updatedAt: new Date(now - 12_000).toISOString(),
        transcriptPath: "/Users/local/.codex/sessions/current.jsonl",
        usage: { inputTokens: 164820, outputTokens: 2840, cachedInputTokens: 102400, totalTokens: 167660, contextTokens: 164820, contextWindow: 258400 },
        rateLimits: { primary: { usedPercent: 28 } },
      },
      {
        id: "codex-2",
        title: "检查发布流程与构建配置",
        latestContent: "发布配置检查完成，正在整理需要调整的构建参数。",
        cwd: "/Users/local/Projects/client-app",
        model: "gpt-5.6-terra",
        effort: "medium",
        status: "idle",
        source: "Codex Desktop",
        updatedAt: new Date(now - 18 * 60_000).toISOString(),
        transcriptPath: "/Users/local/.codex/sessions/build.jsonl",
        usage: { inputTokens: 90360, outputTokens: 1970, cachedInputTokens: 64120, totalTokens: 92330, contextWindow: 258400 },
      },
      {
        id: "codex-3",
        title: "修复同步客户端连接问题",
        latestContent: "连接恢复后已完成一次完整的数据同步。",
        cwd: "/Users/local/Projects/sync-client",
        model: "gpt-5.5",
        effort: "medium",
        status: "idle",
        source: "Codex CLI",
        updatedAt: new Date(now - 86 * 60_000).toISOString(),
        transcriptPath: "/Users/local/.codex/sessions/sync.jsonl",
        usage: { inputTokens: 53440, outputTokens: 1380, cachedInputTokens: 29360, totalTokens: 54820, contextWindow: 200000 },
      },
    ],
  },
  claude: {
    id: "claude",
    label: "Claude Desktop",
    installed: true,
    running: true,
    desktopPath: "/Applications/Claude.app",
    cliPath: "/opt/homebrew/bin/claude",
    dataHome: "/Users/local/.claude",
    processes: [{ pid: 532, name: "Claude", command: "/Applications/Claude.app/Contents/MacOS/Claude", elapsed: "01:49:50" }],
    totals: { inputTokens: 286440, outputTokens: 7420, cachedInputTokens: 178240, totalTokens: 293860, totalCostUsd: 18.42 },
    stats: {
      totalSessions: 128,
      totalMessages: 1840,
      firstSessionDate: "2026-05-18",
      lastComputedDate: new Date(now).toISOString(),
      modelUsage: [
        { model: "claude-sonnet-5", costUSD: 12.6 },
        { model: "claude-opus-5", costUSD: 5.82 },
      ],
      path: "/Users/local/.claude/stats-cache.json",
    },
    agents: [{ sessionId: "claude-1" }],
    planUsage: {
      sampledAt: new Date(now - 2 * 60_000).toISOString(),
      stale: false,
      path: "/Users/local/Library/Application Support/Claude/plan-usage-history.json",
      windows: {
        fiveHour: { usedPercent: 18, remainingPercent: 82 },
        sevenDay: { usedPercent: 31, remainingPercent: 69 },
      },
    },
    errors: [],
    sessions: [
      {
        id: "claude-1",
        title: "梳理服务端模块依赖关系",
        latestContent: "我正在核对模块之间的调用关系和循环依赖。",
        cwd: "/Users/local/Projects/api-server",
        model: "claude-sonnet-5",
        effort: "high",
        status: "running",
        source: "Claude Code",
        permissionMode: "acceptEdits",
        updatedAt: new Date(now - 8_000).toISOString(),
        transcriptPath: "/Users/local/.claude/projects/api/current.jsonl",
        usage: { inputTokens: 72800, outputTokens: 3160, cachedInputTokens: 48600, cacheCreationTokens: 11200, totalTokens: 135760, contextTokens: 72800, contextWindow: 200000 },
      },
      {
        id: "claude-2",
        title: "更新本地代理启动说明",
        latestContent: "启动说明已经更新，并补充了常见故障的排查步骤。",
        cwd: "/Users/local/Projects/local-proxy",
        model: "claude-sonnet-5",
        effort: "medium",
        status: "idle",
        source: "Claude Code",
        permissionMode: "manual",
        updatedAt: new Date(now - 34 * 60_000).toISOString(),
        transcriptPath: "/Users/local/.claude/projects/proxy/session.jsonl",
        usage: { inputTokens: 48620, outputTokens: 1840, cachedInputTokens: 29300, cacheCreationTokens: 7800, totalTokens: 87560, contextWindow: 200000 },
      },
    ],
  },
};
